#ifndef SRC_IOMAP_H_
#define SRC_IOMAP_H_
//#define ARMNOWORK
//#define rb2
#define reversegyro
//#define rb2017
//#define ARM_TEST
//#define rb2
//#define NOVISION

#ifndef rb2017
#define PWM_OUT_DRIVE_LEFT 0
#define PWM_OUT_DRIVE_RIGHT 1

#else
//PWM Out
#define PWM_OUT_DRIVE_LEFT 0
#define PWM_OUT_MINI_LEFT 1
#define PWM_OUT_DRIVE_RIGHT 3
#define PWM_OUT_MINI_RIGHT 2
#endif

#define CAN_OUT_CUBE_INTAKE_LEFT 2
#define CAN_OUT_CUBE_INTAKE_RIGHT 3
#define CAN_OUT_CUBE_ARM 4
#define CAN_OUT_CUBE_HAND 5
#ifdef rb2
#define CAN_OUT_LIFT_LEFT 7
#define CAN_OUT_LIFT_RIGHT 6
#else
#define CAN_OUT_LIFT_LEFT 6
#define CAN_OUT_LIFT_RIGHT 7
#endif
#define CAN_PNUEMATICS 0

#define DIGITAL_IN_DRIVE_LEFT_ENCODER 0
#define DIGITAL_IN_DRIVE_RIGHT_ENCODER 2
#define DIGITAL_IN_ARM_FRONT_LIMIT 1
#define DIGITAL_IN_ARM_BACK_LIMIT 3
#define DIGITAL_IN_INTAKE_DEPLOYED 4
#define DIGITAL_IN_LIFT_LEFT_ENCODER 5
#define DIGITAL_IN_LIFT_RIGHT_ENCODER 6
#define DIGITAL_IN_LIFT_LEFT_LIMIT 7
#define DIGITAL_IN_LIFT_RIGHT_LIMIT 8
#define DIGITAL_IN_HAND_CUBE_PRESENT 9

#define PCM_OUT_INTAKE_RAISE 1
#define PCM_OUT_INTAKE_LOWER 0
#define PCM_OUT_ARM_BRAKE_DISENGAGE 2
#define PCM_OUT_ARM_BRAKE_ENGAGE 3
#define PCM_OUT_ARM_HAND_RELEASE 4
#define PCM_OUT_ARM_HAND_TIGHTEN 5
#define PCM_OUT_RAMP_HOLD 7
#define PCM_OUT_RAMP_DEPLOY 6

#define ANALOG_IN_DRIVE_GYRO 1
#define ANALOG_IN_ARM_POT 2



#endif /* SRC_IOMAP_H_ */
